name: find_and_extend
owner: peterjc
homepage_url: https://github.com/peterjc/galaxy_blast/tree/master/tools/find_and_extend
repository_url: https://github.com/peterjc/galaxy_blast/tree/master/tools/find_and_extend
description: BLAST find and extend
long_description: |
  Given query sequences(), finds their best full length hit in a BLAST database,
  and returns the matching sequences extended upstream and downstream. Intended
  for use in extracting target regions for tasks like primer or KASP marker design
  given a short marker like candidate alleles from genotyping by sequencing.
categories:
- Fasta Manipulation
- Sequence Analysis
type: unrestricted
include:
- strip_components: 2
  source:
  - ../../tools/find_and_extend/README.rst
  - ../../tools/find_and_extend/find_and_extend.py
  - ../../tools/find_and_extend/find_and_extend.xml
  - ../../tools/find_and_extend/tool_dependencies.xml
  - ../../test-data/blastdb.loc
  - ../../test-data/rhodopsin_fragment.fasta
  - ../../test-data/rhodopsin_fragment.tabular
  - ../../test-data/rhodopsin_nucs.fasta.nhd
  - ../../test-data/rhodopsin_nucs.fasta.nhi
  - ../../test-data/rhodopsin_nucs.fasta.nhr
  - ../../test-data/rhodopsin_nucs.fasta.nin
  - ../../test-data/rhodopsin_nucs.fasta.nog
  - ../../test-data/rhodopsin_nucs.fasta.nsd
  - ../../test-data/rhodopsin_nucs.fasta.nsi
  - ../../test-data/rhodopsin_nucs.fasta.nsq
  - ../../test-data/rhodopsin_nucs.fasta.nnd
  - ../../test-data/rhodopsin_nucs.fasta.nni
